apiVersion: v1
kind: Service
metadata:
  namespace: team-services
  name: efx-service
spec:
  ports:
  - port: 80
    targetPort: http-web
  selector:
    app: efx-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: team-services
  name: efx-svc-deployment
spec:
  selector:
    matchLabels:
      app: efx-svc
  template:
    metadata:
      labels:
        app: efx-svc
    spec:
      terminationGracePeriodSeconds: 35
      containers:
      - name: dotnet
        image: mcr.microsoft.com/dotnet/samples:aspnetapp
        env:
        - name: Database__ConnectionString
          value: "TEST"
        livenessProbe:
          tcpSocket:
            port: 80
        ports:
        - containerPort: 80
          protocol: TCP
          name: http-web

