{
 "title": "all pods",
 "panels": [
  {
   "title": "Memory Working Set",
   "type": "singlestat",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",instance=~\"^$instance$\"}) / sum (machine_memory_bytes{instance=~\"^$instance$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "singlestat",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\",instance=~\"^$instance$\"}[1m])) / sum (machine_cpu_cores{instance=~\"^$instance$\"}) * 100"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "singlestat",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{id=\"/\",instance=~\"^$instance$\"}) / sum(container_fs_limit_bytes{id=\"/\",instance=~\"^$instance$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\",instance=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{instance=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",instance=~\"^$instance$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{instance=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{id=\"/\",instance=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{id=\"/\",instance=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "yaxes": [
    { "format": "Bps", "label": "transmit / receive" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"^$instance$\",namespace=~\"^$namespace$\"}[1m]))",
     "legendFormat": "receive"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{instance=~\"^$instance$\",namespace=~\"^$namespace$\"}[1m]))",
     "legendFormat": "transmit"
    }
   ]
  }
 ]
}
{
 "title": "each pod",
 "panels": [
  {
   "title": "Cpu Usage",
   "type": "graph",
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod_name)",
     "legendFormat": "{{`{{ pod_name }}`}}"
    }
   ]
  },
  {
   "title": "Memory Working Set",
   "type": "graph",
   "yaxes": [
    { "format": "bytes", "label": "used" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$instance$\",namespace=~\"^$namespace$\"}) by (pod_name)",
     "legendFormat": "{{`{{ pod_name }}`}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "yaxes": [
    { "format": "Bps", "label": "transmit / receive" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$instance$\",namespace=~\"^$namespace$\"}[1m])) by (pod_name)",
     "legendFormat": "{{`{{ pod_name }}`}} < in"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$instance$\",namespace=~\"^$namespace$\"}[1m])) by (pod_name)",
     "legendFormat": "{{`{{ pod_name }}`}} > out"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "graph",
   "yaxes": [
    { "format": "bytes", "label": "used" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$instance$\",namespace=~\"^$namespace$\"}) by (pod_name)",
     "legendFormat": "{{`{{ pod_name }}`}}"
    }
   ]
  }
 ]
}
{
 "title": "ASP.NET Core Metrics",
 "description": "Shows HTTP statistics for ASP.NET Core Services.",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "HTTP Status Codes by Service",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(app,kubernetes_namespace, code)(rate(http_requests_received_total[5m]))"
    }
   ]
  },
  {
   "title": "Live Requests (In-flight)",
   "type": "graph",
   "description": "Set of live HTTP requests in-progress by app / service.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(app,kubernetes_namespace)(application_httprequests_active)"
    },
    {}
   ]
  },
  {
   "title": "HTTP Requests per Second",
   "type": "graph",
   "description": "HTTP requests by second per service",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(app,kubernetes_namespace)(irate(application_httprequests_transactions_count[5m]))"
    },
    {}
   ]
  },
  {
   "title": "HTTP Requests per Second (Hosts)",
   "type": "graph",
   "description": "HTTP requests by second per service by host.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(app,host,kubernetes_namespace)(irate(application_httprequests_transactions_count[5m]))"
    },
    {}
   ]
  }
 ]
}
{
 "title": "Akka.NET Cluster Metrics",
 "description": "System-wide Akka.NET metrics used for profiling Akka.NET performance",
 "tags": [
  "akka.net",
  "phobos"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "role", "label": "Role", "query": "label_values(cluster_role)" },
   { "name": "address", "label": "address", "query": "label_values(akka_address)" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Cluster Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Cluster Size",
   "type": "stat",
   "description": "Total number of active Akka.Cluster Members.",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ceil(avg(akka_net_akka_cluster_members{status=\"Up\"}))",
     "legendFormat": "Up"
    },
    {
     "expr": "ceil(avg(akka_net_akka_cluster_members{status=\"WeaklyUp\"}))",
     "legendFormat": "WeaklyUp"
    },
    {
     "expr": "ceil(avg(akka_net_akka_cluster_members{status=\"Joining\"}))",
     "legendFormat": "Joining"
    },
    {
     "expr": "ceil(avg(akka_net_akka_cluster_members{status=\"Leaving\"}))",
     "legendFormat": "Leaving"
    },
    {
     "expr": "ceil(avg(akka_net_akka_cluster_members{status=\"Exiting\"}))",
     "legendFormat": "Exiting"
    },
    {
     "expr": "ceil(avg(akka_net_akka_cluster_members{status=\"Down\"}))",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Unreachable Nodes",
   "type": "stat",
   "description": "All nodes in the cluster that are detected to be unreachable.",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ceil(avg(akka_net_akka_cluster_reachable))"
    }
   ]
  },
  {
   "title": "Cluster Nodes by Status",
   "type": "graph",
   "description": "Tracks all nodes by their membership status and reachability.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(avg by(status)(akka_net_akka_cluster_members))",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "ceil(avg(akka_net_akka_cluster_reachable))",
     "legendFormat": "Unreachable"
    }
   ]
  },
  { "title": "Logging and Error Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Cluster Logging Activity",
   "type": "graph",
   "description": "Total aggregate logging activity per-second for each node in an Akka.NET cluster.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(level)(increase(akka_net_akka_logs{cluster_role=~\"$role\",akka_address=~\"$address\"}[1m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Exceptions by Type (over 5m)",
   "type": "table-old",
   "description": "Groups all exceptions detected in Akka.NET logs by type.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by(cluster_role,akka_address,exceptiontype)(ceil(increase(akka_net_akka_logs{cluster_role=~\"$role\",akka_address=~\"$address\",exceptiontype=~\".+\"}[5m])))"
    }
   ]
  },
  {
   "title": "Total Errors Logged (5m)",
   "type": "stat",
   "description": "Total errors logged by Akka.NET over past 5 minutes, cumulative for all roles / cluster / exception types.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(akka_net_akka_logs{level=\"error\",cluster_role=~\"$role\",akka_address=~\"$address\"}[5m]))"
    }
   ]
  },
  { "title": "Actor Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }, "repeat": "role" },
  {
   "title": "Total Akka.NET Actors",
   "type": "graph",
   "description": "The full set of Akka.NET actors running on all nodes for all roles in a cluster.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster_role,akka_address)(akka_net_akka_actor_created{cluster_role=~\"$role\",akka_address=~\"$address\"}) - sum by(cluster_role,akka_address)(akka_net_akka_actor_stopped{cluster_role=~\"$role\",akka_address=~\"$address\"})",
     "legendFormat": "Total Actors [{{cluster_role}} ({{akka_address}})]"
    }
   ]
  },
  {
   "title": "Total Actor Throughput (msg/s)",
   "type": "stat",
   "description": "Cumulative Akka.NET messaging throughput across all selected nodes and roles.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(akka_net_akka_messages_recv_total{cluster_role=~\"$role\",akka_address=~\"$address\"}[1m]))"
    }
   ]
  },
  {
   "title": "Live Actors by Type (Top 10)",
   "type": "table-old",
   "description": "Top 10 actor starts / stops by type.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "topk(10,sum by(actortype)(akka_net_akka_actor_created{cluster_role=~\"$role\",akka_address=~\"$address\"}))",
     "legendFormat": "{{actortype}} created"
    },
    {
     "expr": "topk(10,sum by(actortype)(akka_net_akka_actor_stopped{cluster_role=~\"$role\",akka_address=~\"$address\"}))",
     "legendFormat": "{{actortype}} terminated"
    }
   ]
  },
  {
   "title": "Actor Crashes by Actor / Exception (Top 10)",
   "type": "table",
   "description": "Top 10 actor type / exception type pairs, based on the number of crashes per second observed over a 30 minute timespan.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "topk(10,sum by(actortype, exceptiontype)(rate(akka_net_akka_actor_restarts[30m])))",
     "legendFormat": "{{actortype}},{{exceptiontype}}"
    }
   ]
  },
  {
   "title": "Akka.NET Message Throughput by Type  (Top 10)",
   "type": "bargauge",
   "description": "Akka.NET message throughput by message type.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10,sum by(messagetype)(rate(akka_net_akka_messages_recv_total{cluster_role=~\"$role\",akka_address=~\"$address\"}[5m])))",
     "legendFormat": "{{messagetype}}"
    }
   ]
  },
  {
   "title": "Akka.NET Message Totals by Type  (Top 10 over 5 minutes)",
   "type": "bargauge",
   "description": "Akka.NET message throughput by message type.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10,sum by(messagetype)(increase(akka_net_akka_messages_recv_total{cluster_role=~\"$role\",akka_address=~\"$address\"}[5m])))",
     "legendFormat": "{{messagetype}}"
    }
   ]
  }
 ]
}