apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: default
  source:
    chart: rabbitmq
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 10.3.9
    helm:
      releaseName: rabbitmq
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: default