apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: default
  source:
    chart: argo-workflows
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.19.1
    helm:
      releaseName: argo-workflows
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: argo