apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubemq-cluster
  namespace: argocd
spec:
  project: default
  source:
    chart: kubemq
    repoURL: https://kubemq-io.github.io/charts
    targetRevision: 2.2.11
    helm:
      releaseName: kubemq-cluster
      parameters:
      - name: key
        value: {{ .Values.kubemq.key }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubemq